SET @ST_YYYYMMDD = '2020-11-01';
SET @END_YYYMMDD = '2020-11-30';

SELECT concat(truncate(M.`1회` / M.횟수합 * 100, 2),'%') AS '1회 참여율'
     , concat(truncate(M.`2회` / M.횟수합 * 100, 2),'%') AS '2회 참여율'
     , concat(truncate(M.`3회` / M.횟수합 * 100, 2),'%') AS '3회 참여율'
     , concat(truncate(M.`4회` / M.횟수합 * 100, 2),'%') AS '4회 참여율'
     , concat(truncate(M.`5회` / M.횟수합 * 100, 2),'%') AS '5회 참여율'
     , concat(truncate(M.`6회` / M.횟수합 * 100, 2),'%') AS '6회 참여율'
     , concat(truncate(M.`7회` / M.횟수합 * 100, 2),'%') AS '7회 참여율'
     , concat(truncate(M.`8회` / M.횟수합 * 100, 2),'%') AS '8회 참여율'
     , concat(truncate(M.`9회` / M.횟수합 * 100, 2),'%') AS '9회 참여율'
     , concat(truncate(M.`10회` / M.횟수합 * 100, 2),'%') AS '10회 참여율'
     , concat(truncate(M.`11회` / M.횟수합 * 100, 2),'%') AS '11회 참여율'
     , concat(truncate(M.`12회` / M.횟수합 * 100, 2),'%') AS '12회 참여율'
     , concat(truncate(M.`13회` / M.횟수합 * 100, 2),'%') AS '13회 참여율'
     , concat(truncate(M.`14회` / M.횟수합 * 100, 2),'%') AS '14회 참여율'
     , concat(truncate(M.`15회` / M.횟수합 * 100, 2),'%') AS '15회 참여율'
     , concat(truncate(M.`16회` / M.횟수합 * 100, 2),'%') AS '16회 참여율'
     , concat(truncate(M.`17회` / M.횟수합 * 100, 2),'%') AS '17회 참여율'
     , concat(truncate(M.`18회` / M.횟수합 * 100, 2),'%') AS '18회 참여율'
     , concat(truncate(M.`19회` / M.횟수합 * 100, 2),'%') AS '19회 참여율'
     , concat(truncate(M.`20회` / M.횟수합 * 100, 2),'%') AS '20회 참여율'
     , concat(truncate(M.`21회` / M.횟수합 * 100, 2),'%') AS '21회 참여율'
     , concat(truncate(M.`22회` / M.횟수합 * 100, 2),'%') AS '22회 참여율'
     , concat(truncate(M.`23회` / M.횟수합 * 100, 2),'%') AS '23회 참여율'
     , concat(truncate(M.`24회` / M.횟수합 * 100, 2),'%') AS '24회 참여율'
     , concat(truncate(M.`25회` / M.횟수합 * 100, 2),'%') AS '25회 참여율'
     , concat(truncate(M.`26회` / M.횟수합 * 100, 2),'%') AS '26회 참여율'
     , concat(truncate(M.`27회` / M.횟수합 * 100, 2),'%') AS '27회 참여율'
     , concat(truncate(M.`28회` / M.횟수합 * 100, 2),'%') AS '28회 참여율'
     , concat(truncate(M.`29회` / M.횟수합 * 100, 2),'%') AS '29회 참여율'
     , concat(truncate(M.`30회` / M.횟수합 * 100, 2),'%') AS '30회 참여율'
 FROM (
    SELECT COUNT(CASE WHEN A.참여횟수 IN(1) THEN 1 END ) AS '1회'
         , COUNT(CASE WHEN A.참여횟수 IN(2) THEN 1 END ) AS '2회'
         , COUNT(CASE WHEN A.참여횟수 IN(3) THEN 1 END ) AS '3회'
         , COUNT(CASE WHEN A.참여횟수 IN(4) THEN 1 END ) AS '4회'
         , COUNT(CASE WHEN A.참여횟수 IN(5) THEN 1 END ) AS '5회'
         , COUNT(CASE WHEN A.참여횟수 IN(6) THEN 1 END ) AS '6회'
         , COUNT(CASE WHEN A.참여횟수 IN(7) THEN 1 END ) AS '7회'
         , COUNT(CASE WHEN A.참여횟수 IN(8) THEN 1 END ) AS '8회'
         , COUNT(CASE WHEN A.참여횟수 IN(9) THEN 1 END ) AS '9회'
         , COUNT(CASE WHEN A.참여횟수 IN(10) THEN 1 END ) AS '10회'
         , COUNT(CASE WHEN A.참여횟수 IN(11) THEN 1 END ) AS '11회'
         , COUNT(CASE WHEN A.참여횟수 IN(12) THEN 1 END ) AS '12회'
         , COUNT(CASE WHEN A.참여횟수 IN(13) THEN 1 END ) AS '13회'
         , COUNT(CASE WHEN A.참여횟수 IN(14) THEN 1 END ) AS '14회'
         , COUNT(CASE WHEN A.참여횟수 IN(15) THEN 1 END ) AS '15회'
         , COUNT(CASE WHEN A.참여횟수 IN(16) THEN 1 END ) AS '16회'
         , COUNT(CASE WHEN A.참여횟수 IN(17) THEN 1 END ) AS '17회'
         , COUNT(CASE WHEN A.참여횟수 IN(18) THEN 1 END ) AS '18회'
         , COUNT(CASE WHEN A.참여횟수 IN(19) THEN 1 END ) AS '19회'
         , COUNT(CASE WHEN A.참여횟수 IN(20) THEN 1 END ) AS '20회'
         , COUNT(CASE WHEN A.참여횟수 IN(21) THEN 1 END ) AS '21회'
         , COUNT(CASE WHEN A.참여횟수 IN(22) THEN 1 END ) AS '22회'
         , COUNT(CASE WHEN A.참여횟수 IN(23) THEN 1 END ) AS '23회'
         , COUNT(CASE WHEN A.참여횟수 IN(24) THEN 1 END ) AS '24회'
         , COUNT(CASE WHEN A.참여횟수 IN(25) THEN 1 END ) AS '25회'
         , COUNT(CASE WHEN A.참여횟수 IN(26) THEN 1 END ) AS '26회'
         , COUNT(CASE WHEN A.참여횟수 IN(27) THEN 1 END ) AS '27회'
         , COUNT(CASE WHEN A.참여횟수 IN(28) THEN 1 END ) AS '28회'
         , COUNT(CASE WHEN A.참여횟수 IN(29) THEN 1 END ) AS '29회'
         , COUNT(CASE WHEN A.참여횟수 IN(30) THEN 1 END ) AS '30회'
         , COUNT(CASE WHEN A.참여횟수 > 0 AND A.참여횟수 <= 30 THEN 1 END ) AS '횟수합'
      FROM (
        SELECT COUNT( X.LIFE_SEQ_NO ) AS '참여횟수'
             , A.LIFE_SEQ_NO
          FROM WATV_MEMBER.T_DW_WATV_MEMBER A 
           LEFT OUTER JOIN WATV_MYPAGE.T_PRAYER_USER_DATA X ON (X.LIFE_SEQ_NO = A.LIFE_SEQ_NO AND X.YYYYMMDD BETWEEN @ST_YYYYMMDD AND @END_YYYMMDD) 
        WHERE A.NATION_CD = 0 
        GROUP BY X.LIFE_SEQ_NO
    ) A   
) M
;